urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', 'visitas.aplicacao.views.index', name='index'),
    url(r'^sucesso/', 'visitas.aplicacao.views.sucesso', name='sucesso'),
    url(r'^agendar_visita/', 'visitas.aplicacao.views.agendar_visita', name='agendar_visita'),
    url(r'^consulta/', 'visitas.aplicacao.views.consulta', name='consulta'),
    url(r'^media/(.*)$', 'django.views.static.serve', 
        {'document_root': settings.MEDIA_ROOT}),
    (r'^login/', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    (r'^logout/', 'django.contrib.auth.views.logout', {'template_name': 'logout.html', 'next_page': '/login'}),
    url(r'^relatorio', 'visitas.aplicacao.views.relatorio', name='relatorio'),    
)

aplicacao/models.py
#coding: utf-8

from django.db import models
from django.forms import ModelForm, ChoiceField, RadioSelect
from django import forms
from django.db import connection, transaction


class AgendarVisita(models.Model):
    nome_da_escola = models.CharField(max_length=50)
    telefone_de_contato = models.CharField(max_length=50)
    email = models.EmailField()
    quantidade_de_visitantes = models.IntegerField()
    responsavel_escola = models.CharField(max_length=50)
    data = models.CharField(max_length=50)
    horario = models.CharField(max_length=50)
    horario1 = models.CharField(max_length=50, blank=True)
    responsavel1 = models.CharField(max_length=50) 
    responsavel2 = models.CharField(max_length=50, null=True, blank=True) 
    responsavel3 = models.CharField(max_length=50, null=True, blank=True) 
    responsavel4 = models.CharField(max_length=50, null=True, blank=True) 
    responsavel5 = models.CharField(max_length=50, null=True, blank=True) 
    responsavel6 = models.CharField(max_length=50, null=True, blank=True)    


class AgendarVisitaModelForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(AgendarVisitaModelForm, self).__init__(*args, **kwargs)

        nome = ['nome_da_escola']
        for n in nome:
            self.fields[n].widget=forms.TextInput(attrs={'size':'40', 'onkeyup':'maiuscula(this.value);', 'maxlength':'30'})

        responsavel_escola = ['responsavel_escola']
        for r in responsavel_escola:
            self.fields[r].widget=forms.TextInput(attrs={'size':'40', 'onkeyup':'maiuscula(this.value);', 'maxlength':'29'})

        responsavel = ['responsavel1']
        for r in responsavel:
            self.fields[r].widget=forms.TextInput(attrs={'size':'40', 'onkeyup':'maiuscula(this.value);', 'maxlength':'29'})
            
        responsavel = ['responsavel2']
        for r in responsavel:
            self.fields[r].widget=forms.TextInput(attrs={'size':'40', 'onkeyup':'maiuscula(this.value);', 'maxlength':'29'})
            
        responsavel = ['responsavel3']
        for r in responsavel:
            self.fields[r].widget=forms.TextInput(attrs={'size':'40', 'onkeyup':'maiuscula(this.value);', 'maxlength':'29'})
            
        responsavel = ['responsavel4']
        for r in responsavel:
            self.fields[r].widget=forms.TextInput(attrs={'size':'40', 'onkeyup':'maiuscula(this.value);', 'maxlength':'29'})
            
        responsavel = ['responsavel5']
        for r in responsavel:
            self.fields[r].widget=forms.TextInput(attrs={'size':'40', 'onkeyup':'maiuscula(this.value);', 'maxlength':'29'})
            
        responsavel = ['responsavel6']
        for r in responsavel:
            self.fields[r].widget=forms.TextInput(attrs={'size':'40', 'onkeyup':'maiuscula(this.value);', 'maxlength':'29'})

        telefone = ['telefone_de_contato']
        for tel in telefone:
            self.fields[tel].widget=forms.TextInput(attrs={'size':'40'})

        email = ['email']
        for e in email:
            self.fields[e].widget=forms.TextInput(attrs={'size':'40', 'onkeyup':'minuscula(this.value);', 'maxlength':'30'})

        visitantes = ['quantidade_de_visitantes']
        for v in visitantes:
            self.fields[v].widget=forms.TextInput(attrs={'size':'40', 'onkeyup':'num(this);', 'maxlength':'3'})

        lista_data = ['data']
        for dia in lista_data:
            self.fields[dia].widget = forms.HiddenInput()

        lista_horario1 = ['horario1']
        for hora1 in lista_horario1:
            data = '08/09/2011'
            self.fields[hora1].widget = forms.RadioSelect(attrs={'onclick':'data.value = "08/09/2011"; this.name = "horario", document.getElementByName(horario).checked = false;'}, choices=
(('14:00', '14:00 - Disponível '+str(160 - self.conta_horario('14:00', data)) + ' vaga(s)'), ('15:00', '15:00 - Disponível '+str(160 - self.conta_horario('15:00', data)) +  ' vaga(s)'), ('16:00', '16:00 - Disponível ' +str(160 - self.conta_horario('16:00', data)) + ' vaga(s)'), ('17:00', '17:00 - Disponível '+str(160 - self.conta_horario('17:00', data)) +  ' vaga(s)'), ('18:00', '18:00 - Disponível '+str(160 - self.conta_horario('18:00', data)) + ' vaga(s)'), ('19:00', '19:00 - Disponível '+str(160 - self.conta_horario('19:00', data)) + ' vaga(s)')))
        lista_horario = ['horario']
        for hora in lista_horario:
            data = '09/09/2011'
            self.fields[hora].widget = forms.RadioSelect(attrs={'onclick':'data.value = "09/09/2011"'}, choices=
(('14:00', '14:00 - Disponível '+str(160 - self.conta_horario('14:00', data)) + ' vaga(s)'), ('15:00', '15:00 - Disponível '+str(160 - self.conta_horario('15:00', data)) +  ' vaga(s)'), ('16:00', '16:00 - Disponível ' +str(160 - self.conta_horario('16:00', data)) + ' vaga(s)'), ('17:00', '17:00 - Disponível '+str(160 - self.conta_horario('17:00', data)) +  ' vaga(s)'), ('18:00', '18:00 - Disponível '+str(160 - self.conta_horario('18:00', data)) + ' vaga(s)'), ('19:00', '19:00 - Disponível '+str(160 - self.conta_horario('19:00', data)) + ' vaga(s)')))
        
    def conta_horario(self, horario, data):
        cursor = connection.cursor()
        cursor.execute("SELECT sum(quantidade_de_visitantes) from aplicacao_agendarvisita where horario = %s and data = %s;", [horario, data])
        row = cursor.fetchone()
        row = str(row)
        if row == '(None,)':
            return 0
        else:            
            row = row.split("(")[1]
            row = row.split("L,)")[0]
            return int(row) 

    class Meta:
        model = AgendarVisita	
       

aplicacao/views.py
# coding: utf-8 

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from visitas.aplicacao.models import AgendarVisita, AgendarVisitaModelForm
from django.core.urlresolvers import reverse
from django.core.mail import send_mail, get_connection, EmailMessage
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
import os
from django.core.urlresolvers import reverse
from cStringIO import StringIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from django.contrib.auth.decorators import login_required
from django.db import connection, transaction

#pagina principal
def index(request):
	return render_to_response('index.html', {'user':request.user})

#agendamento de visita
@login_required
def agendar_visita(request):
    i = []
    f = AgendarVisitaModelForm()
    
    #validação do formulario com a quantidade de visitantes
    if request.GET:
    
        #se quantidade de visitantes for igual a em branco, quantidade recebe zero, senão recebe o valor passado pelo usuário
        if str(request.GET['quantidade_de_visitantes']) == '':
            quantidade = 0
        else:
            quantidade = int(request.GET['quantidade_de_visitantes'])
            
        #se a quantidade for maior que zero e menor ou igual a 160, o contador i é implementado para gerar o os campos de responsáveia pela visita, onde a cada 30 visitantes, é necessário um responsavel.
        if quantidade > 0 and quantidade <= 160:
            i = quantidade/30
            if (i < 1) and (i >= 0):
                i = 1
            elif (i >= 1) and (quantidade % 30 != 0):
                i += 1
                
            #retorna o template com o restante do formulário, com as informações do usuario logado 'user', o contador 'i', para a geração dos campos de responsáveis
            return render_to_response('agendar_visita.html', {'form': f, 'user': request.user, 'i': i, 'visitantes': request.GET['quantidade_de_visitantes']})
            
        #retorna o formulario com a mensagem de erro
        else:        
            erro = True
            if quantidade == 0:
                if str(request.GET['quantidade_de_visitantes']) == '':
                    texto_erro = 'Campo Obrigatório.'
                elif str(request.GET['quantidade_de_visitantes']) == '0':
                    texto_erro = 'Quantidade de visitantes não pode ser zero.'
            elif quantidade > 160:
                texto_erro = 'Quantidade de visitantes não pode ser superior a 160 participantes.'
            return render_to_response('agendar.html', {'form':f, 'user':request.user, 'erro':erro, 'texto_erro':texto_erro})
    #validação do formulario de agendamento
    elif request.POST:
        
        #geração do contador de responsaveis, que será chamado, caso as informações não sejam válidas (erro)
        if str(request.POST['quantidade_de_visitantes']) == '':
            quantidade = 0
        else:
            quantidade = int(request.POST['quantidade_de_visitantes'])
        if quantidade > 0 and quantidade <= 160:
            i = quantidade/30
            if (i < 1) and (i >= 0):
                i = 1
            elif (i >= 1) and (quantidade % 30 != 0):
                i += 1
         
        #f recebe o valor de todos os campos do formulario
        f = AgendarVisitaModelForm(request.POST)
        
        #valida o campo quantidade de visitantes e passa o valor 0 se campo estiver em branco; se o campo estiver preenchido corretamente passa o valor informado pelo usuário 
        if request.POST['quantidade_de_visitantes'] == '':
            quantidade_visitantes = 0
        else:
            quantidade_visitantes = int(request.POST['quantidade_de_visitantes'])
        
        #se todos os campos obrigatórios foram preenchidos
        if f.is_valid():
        
            #verifica se existe a quantidade de vagas solicitadas pelo usuário
            visitantes = f.conta_horario(request.POST['horario'], request.POST['data'])+ quantidade_visitantes
            
            #se o total de visitantes for menor ou igual a 160, salva os dados no banco de dados, envia e-mail para o solicitante e para o responsavel pelo evento e retorna a página de confirmação para usuário imprimir os dados referente ao agendamento da visita
            if visitantes <= 160:
            
                #salva o formulario
                f.save()
                
                #dados do email: titulo (subject) e mensagem
                subject = "Confirmação: Visitas de Escolas - Semana do Saber Fazer Saber"
                mensagem = ('Olá ' + str(request.POST['responsavel_escola']) + ', a visita da ' + str(request.POST['nome_da_escola']) + ' na Semana do Saber Fazer Saber foi agendada para o dia ' + str(request.POST['data']) + ' às ' + str(request.POST['horario']) + ', no Auditório Miguel Ramalho.')
                
                #remetente da mensagem
                from_email = '' #colocar o email
                
                #login e senha do remetente da mensagem, neste caso foi configurado os serviços do gmail; caso queira trocar o serviço de e-mail, deve trocar a conexão no arquivo "settings.py" do projeto
                connection = get_connection(username = '', password ='') #colocar o e-mail e a senha
                
                #e-mail do responsavel pelo evento
                email_gerencia = '' #colocar e-mail do responsavel
                
                #agrupa as informações do e-mail
                send_email = EmailMessage(subject, mensagem , from_email, [request.POST['email'], email_gerencia], connection = connection)
                send_email.content_subtype = "html"
                
                #envia o e-mail para o solicitante da visita "request.POST['email']", com cópia para o responsavel pelo evento
                send_email.send()
                
                #retorna o template de confirmação
                return HttpResponseRedirect(reverse('visitas.aplicacao.views.sucesso'))
                
            #se o total de visitantes for superior a 160, retorna o template de formulario, informando a impossibilidade de agendamento da visita para a data e hora escolhida
            elif visitantes > 160:
                erro_vagas = True
                texto_erro = "Não há " + str(request.POST['quantidade_de_visitantes']) + " vagas disponíveis para o dia " + str(request.POST['data']) + " às " + str(request.POST['horario']) + ". Por favor, escolha outra data e horário."
                return render_to_response('agendar_visita.html',{'form':f, 'erro_vagas':erro_vagas, 'texto_erro':texto_erro, 'user':request.user, 'i':i, 'visitantes': request.POST['quantidade_de_visitantes'] })
                
        #se algum campo obrigatório não foi informado, retorna o template do formulario, informando e erro
        else:
            erro=True
            return render_to_response('agendar_visita.html',{'form':f, 'erro':erro, 'user':request.user, 'i':i, 'visitantes': request.POST['quantidade_de_visitantes'] })
            
    #se o metodo não for GET (não foi submetido o formulario com a quantidade de visitantes), nem POST (não foi submetido o formulario de agendamento de visitas, retorna o formulario para preenchimento da quantidade de visitantes, começando o agendamento da visita)
    else:
        f = AgendarVisitaModelForm()
        return render_to_response('agendar.html', {'form':f, 'user': request.user})

#pagina de confirmação após submeter o formulario
@login_required
def sucesso(request):
	return render_to_response('sucesso.html', {'user':request.user})

#relatorio de visitas
@login_required
def relatorio(request):

    #restringe o acesso ao relatório aos usuários gerencia e admin
    if request.user.username == 'admin' or request.user.username == 'gerencia':
    
        #cria as propriedades do pdf
        response = HttpResponse(mimetype='application/pdf')
        response['Content-Disposition'] = 'attachment; filename=visitas.pdf'
        doc = SimpleDocTemplate(response, pagesize = (1000.00, 800.00))
        elements = []
        
        #cria um paragrafo para adicionar a logo da instituição
        styles=getSampleStyleSheet()
        logo = '<img src="/home/dtic/visitas/aplicacao/media/images/logo.png"/> <br><br>'
        elements.append(Paragraph(logo, styles["Normal"]))
        #cria um paragrafo para adicionar o título do relatório
        ptext = '<font size=15> <b> Agendamento de Visitas - Semana do Saber Fazer Saber <b> </font> <br><br><br><br>'
        elements.append(Paragraph(ptext, styles["Normal"]))    
        
        # cria consulta a base de dados, ordenado por data e horário da visita
        data = []        
        visita = AgendarVisita.objects.order_by('data', 'horario')
        
        #cria e adiciona a tabela com os dados da consulta
        for v in visita:
            data.append([Paragraph("<b>ESCOLA</b>", styles["Normal"]), Paragraph("<b>QUANTIDADE DE VISITANTES</b>", styles["Normal"]), Paragraph("<b>DATA E HORÁRIO DA VISITA</b>", styles["Normal"])])
            data.append([v.nome_da_escola, v.quantidade_de_visitantes, str(v.data) + ' às ' + str(v.horario)])
            data.append([Paragraph("<b>RESPONSÁVEL PELA ESCOLA</b>", styles["Normal"]), Paragraph("<b>TELEFONE</b>", styles["Normal"]), Paragraph("<b>E-MAIL</b>", styles["Normal"])])
            data.append([v.responsavel_escola, v.telefone_de_contato, v.email])
            data.append([Paragraph("<b>RESPONSÁVEL PELA VISITA</b>", styles["Normal"])])
            data.append([Paragraph("<b>RESPONSÁVEL PELO GRUPO 1</b>", styles["Normal"]), Paragraph("<b>RESPONSÁVEL PELO GRUPO 2</b>", styles["Normal"]), Paragraph("<b>RESPONSÁVEL PELO GRUPO 3</b>", styles["Normal"])])

aplicacao/templates/agendar.html
{% extends 'base.html' %}
{% block scripts %}
    <script type="text/javascript" src="/media/script.js"></script>
    <script type="text/javascript" src="/media/jquery.js"></script>
    <script type="text/javascript" src="/media/maskedinput.js"></script>
    <script type="text/javascript">
        $.noConflict( )
        jQuery(function($){
            $("#id_telefone_de_contato").mask("(99) 9999-9999");
        });
        function num(dom){
    	    dom.value=dom.value.replace(/\D/g,'');
        }
        function maiuscula(valor){
            var elemento=document.form;
            elemento.nome_da_escola.value=elemento.nome_da_escola.value.toUpperCase();
            elemento.responsavel_pela_visita.value=elemento.responsavel_pela_visita.value.toUpperCase();
            elemento.responsavel_escola.value=elemento.responsavel_escola.value.toUpperCase();
        }
        function minuscula(valor){
            var elemento=document.form;
            elemento.email.value=elemento.email.value.toLowerCase();
        }
    </script> 
{% endblock scripts %}
{% block subtitle %}
    <center> Agendamento de Visitas </center>
{% endblock subtitle %}
{% block conteudo %}
    <form name="form" action="" enctype="multipart/form-data" method="get">
        <table>
            <fildset>                            
                <tr><td>&nbsp;</td></tr>                            
                 <tr>
                    <th>
                        Informe a quantidade de visitantes:
                        {% if erro %}
                            <ul class="errorlist">
                                <li>{{texto_erro}}</li>
                            </ul>
                    	{% endif %}
                    </th>
                </tr>
                <tr><td colspan="2">{{form.quantidade_de_visitantes}}</td></tr>
        </fieldset>
        <tr>
            <td><input type="submit" value="Continuar"/></td>
	    </tr>
	</table>
</form>   
{% endblock conteudo %}

aplicacao/templates/agendar_visita.html
{% extends 'base.html' %}
{% block scripts %}
    <script type="text/javascript" src="/media/script.js"></script>
    <script type="text/javascript" src="/media/jquery.js"></script>
    <script type="text/javascript" src="/media/maskedinput.js"></script>
    <script type="text/javascript">
        $.noConflict( )
        jQuery(function($){
            $("#id_telefone_de_contato").mask("(99) 9999-9999");
        });
        function num(dom){
    	    dom.value=dom.value.replace(/\D/g,'');
        }
        function maiuscula(valor){
            var elemento=document.form;
            elemento.nome_da_escola.value=elemento.nome_da_escola.value.toUpperCase();
            elemento.responsavel_escola.value=elemento.responsavel_escola.value.toUpperCase();
            elemento.responsavel1.value=elemento.responsavel1.value.toUpperCase();
            elemento.responsavel2.value=elemento.responsavel2.value.toUpperCase();
            elemento.responsavel3.value=elemento.responsavel3.value.toUpperCase();
            elemento.responsavel4.value=elemento.responsavel4.value.toUpperCase();
            elemento.responsavel5.value=elemento.responsavel5.value.toUpperCase();
            elemento.responsavel6.value=elemento.responsavel6.value.toUpperCase();
            
        }
        function minuscula(valor){
            var elemento=document.form;
            elemento.email.value=elemento.email.value.toLowerCase();
        }
    </script> 
{% endblock scripts %}
{% block subtitle %}
    <center> Agendamento de Visitas </center>
{% endblock subtitle %}
{% block conteudo %}
    <form name="form" action="agendar_visita" enctype="multipart/form-data" method="post">
        <table>
            <fildset>                            
                <tr><td>&nbsp;</td></tr>                            
                <tr>
                    <th>
                        Escola:
                        {% if erro %}
                            {{form.nome_da_escola.errors}}
              			{% endif %}
                    </th>
                </tr>
                <tr><td colspan="2">{{form.nome_da_escola}}</td></tr>
                <tr>
                    <th>
                        Responsável pela Escola:
                        {% if erro %}
              			    {{form.responsavel_escola.errors}}
           			    {% endif %}
                    </th>
                </tr>
                <tr><td colspan="2">{{form.responsavel_escola}}</td></tr>
                <tr>
                    <th>
                        Responsável pela Visita:
                    </th>
                </tr>
                {% if i >= 1 %}
                    <tr><td>Responsável pelo Grupo 1</td></tr>
                    <tr>
                        <td>
                            {% if erro %}
              			        {{form.responsavel1.errors}}
           			        {% endif %}
           			    </td>
           			</tr>
                    <tr><td colspan="2">{{form.responsavel1}}</td></tr>
                {% endif %}
                {% if i >= 2 %}
                    <tr><td>Responsável pelo Grupo 2</td></tr>
                    <tr>
                        <td>
                            {% if erro %}
              			        {{form.responsavel1.errors}}
           			        {% endif %}
           			    </td>
           			</tr>
                    <tr><td colspan="2">{{form.responsavel2}}</td></tr>
                {% endif %}
                {% if i >= 3 %}
                    <tr><td>Responsável pelo Grupo 3</td></tr>
                    <tr>
                        <td>
                            {% if erro %}
              			        {{form.responsavel1.errors}}
           			        {% endif %}
           			    </td>
           			</tr>
                    <tr><td colspan="2">{{form.responsavel3}}</td></tr>
                {% endif %}
                {% if i >= 4 %}
                    <tr><td>Responsável pelo Grupo 4</td></tr>
                    <tr>
                        <td>
                            {% if erro %}
              			        {{form.responsavel1.errors}}
           			        {% endif %}
           			    </td>
           			</tr>
                    <tr><td colspan="2">{{form.responsavel4}}</td></tr>
                {% endif %}
                {% if i >= 5 %}
                    <tr><td>Responsável pelo Grupo 5</td></tr>
                    <tr>
                        <td>
                            {% if erro %}
              			        {{form.responsavel1.errors}}
           			        {% endif %}
           			    </td>
           			</tr>
                    <tr><td colspan="2">{{form.responsavel5}}</td></tr>
                {% endif %}
                {% if i >= 6 %}
                    <tr><td>Responsável pelo Grupo 6</td></tr>
                    <tr>
                        <td>
                            {% if erro %}
              			        {{form.responsavel1.errors}}
           			        {% endif %}
           			    </td>
           			</tr>
                    <tr><td colspan="2">{{form.responsavel6}}</td></tr>
                {% endif %}
                <tr>
                    <th>
                        Telefone:
                        {% if erro %}
             			    {{form.telefone_de_contato.errors}}
          			    {% endif %}
                    </th>
                </tr>
                <tr><td colspan="2">{{form.telefone_de_contato}}</td></tr>
                <tr>
                    <th>
                        E-mail:
                        {% if erro %}
               			    {{form.email.errors}}
           			    {% endif %}
                    </th>
                </tr>
                <tr><td colspan="2">{{form.email}}</td></tr>
                <tr>
                    <td colspan="2">
                        <input type="hidden" size="40" id="id_quantidade_de_visitantes" onkeyup="num(this);" maxlength="3" name="quantidade_de_visitantes" value={{visitantes}}>
                    </td>
                </tr>
                <tr><td>&nbsp;</td></tr>
                <tr><td>&nbsp;</td></tr>
                <tr>
                    <th align="center">Horários - 08/09/2011:</th>
                    <th align="center">Horários - 09/09/2011:</th>
                </tr>
                <tr>
                    <td align="center" colspan="2">
                        {% if erro %}
                            {{form.horario.errors}}
                        {% endif %}
                        <ul class="errorlist">
                            <li>
                                {% if erro_vagas %}
                                    {{texto_erro}}
                                {% endif %}
                            </li>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>{{form.horario1}}</td>
                    <td>{{form.horario}}</td>
                </tr>
                <tr>
                    <td>{{form.data}}</td>
                </tr>
			</fieldset>
        <tr>
            <td>
                <input type="submit" value="Agendar"/>
                &nbsp;&nbsp;&nbsp;
                <input type="button" value="Voltar" onclick="history.go(-1)">
            </td>
	    </tr>
	</table>
</form>   
{% endblock conteudo %}

aplicacao/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>
            {% block titulo %}Visitas de Escolas - Semana do Saber Fazer Saber{% endblock %}
        </title>
        {% block style %}
            <link rel="stylesheet" type="text/css" href="/media/style.css" media="screen"/>
        {% endblock style %}
        {% block scripts %}
            <script type="text/javascript" src="/media/jquery.js"></script>
            <script type="text/javascript" src="/media/site.js"></script>
        {% endblock scripts %}
    </head>
    <body>
        <div id="wrapper">
            <div id="header">
                <div id="logo"></div>
            	<div id="menu">
                    <ul>
                        <li class="active">
                            <a href="/">Página Inicial</a>
                        </li>
                        <li class="active">
                            <a href="http://www.saberfazersaber.iff.edu.br">Semana do Saber</a>
                        </li>
                        <li class="active">
                            <a href="http://www.iff.edu.br">Portal do IFF</a>
                        </li>
                        {% if not user.is_anonymous %}                            
                            <li class="active">
                                <a href="/logout/">Logout</a>
                            </li>
                            <li> 
                                <b>Bem vindo, {{ user }}!</b>
                            </li>
                        {% else %}
                            <li class="active">
                                <a href="/login/">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
	        </div>
            <div id="page">
                <div id="header-pic"></div>
	            <div id="content">
		            <div class="post">
			            <h2 class="title">{% block subtitle %}{% endblock subtitle %}</h2>
			            <div class="entry">
			                <br></br>
			                <center>
			                    <img src="/media/images/iff.gif" alt="IFF" title="Instituto Federal Fluminense"/>
			                </center>
			                <br/>
			                {% block conteudo %}{% endblock %}
			            </div>			
		            </div>
	            </div>
	            <div id="sidebar">
		            <div id="sidebar-bgtop"></div>
		            <div id="sidebar-content">
			            <div id="sidebar-bgbtm">
			                <ul>
				                <li>
					                <ul>
						                <li><a href="/agendar_visita/">Agendar Visita</a></li>
					                </ul>
				                </li>
				                <li>
					                <ul>
				                        <li><a href="/relatorio">Relatório de Visitas</a></li>
					                </ul>
				                </li>
				                <li>
					                <ul>
				                        <li><a href="/consulta">Consulta de Visitas</a></li>
					                </ul>
				                </li>
			                </ul>
		            </div>
		        </div>
            </div>
    		<div style="clear:both; margin:0;"></div>
        </div>
    </div>
    <div id="footer">
        <p> 
            &copy; Coordenação Adjunta de Administração e Desenvolvimento de Sistemas - IFF Campos-Centro.
            <br>
            <a href="http://www.djangoproject.com/"> Made with Django. </a>
        </p>
    </div> 
  </body>
</html>

aplicacao/templates/index.html
{% extends 'base.html' %}
{% block subtitle %}
    <center>Bem vindo ao Sistema de Visitas </center>
{% endblock subtitle %}
{% block conteudo %}
    <center>
    <p>Período de Inscrição: 00/00/0000 a 00/00/0000.</p>
	<p>
	    Para maiores informações acesse 
		<a href="http://www.iff.edu.br"> Portal do IFF </a>.
	</p>
	</center>
{% endblock conteudo %}

aplicacao/templates/login.html
{% extends 'base.html' %}
{% block subtitle %}
    <center>Login </center>
{% endblock subtitle %}
{% block conteudo %}
    {% if user.is_authenticated %}
        <p><b>Bem vindo, {{ user }}!</b></p>
        <br>
        <p><a href="/logout/">Logout</a></p>
    {% else %}
        {% if form.errors %}
            <ul class="errorlist">
                <li>
                    Usuário e/ou senha incorreta. Tente novamente.
                    <br>
                    Caso persista o problema, entre em contato com a coordenação do evento através do número (00)0000-0000.
                </li>
            </ul>
        {% endif %}
        <form method="post" action="/login/">{% csrf_token %}
            <div class="menu">
                <table>
                    <tr>
                        <td>Login</td>
                        <td>{{ form.username }}</td>
                    </tr>
                    <tr>
                        <td>Senha</td>
                        <td>{{ form.password }}</td>
                    </tr>
                </table>
            </div>
            <input type="submit" value="Login" />
        </form>                            
    {% endif %}    
{% endblock conteudo %}